### ISSUE TITLE
Dropping `git` in gemspec & using Packaging extension

### ISSUE THREAD

**Issue by utkarsh2102** [waiting-for-dev/string-direction#4]
Hi @waiting-for-dev 👋🏻 

Thanks for your great work!
However, whilst maintaining this in Debian, I found some issues that could be fixed by the `Packaging` extension of RuboCop. Would you be interested in doing so?

One specific issue that I'd like to resolve is dropping `git` in the gemspec file.
I'll be happy to raise a PR if you concur with this :)

**Comment by waiting-for-dev** [comment]
Hi @utkarsh2102 ! Thanks for reaching me and for your suggestions.

Yeah, sure, I'd love to incorporate it, alongside a proper CI pipeline including rubocop as we're missing it at this point. I'll try to find the time to fix it, otherwise feel free to submit a pull request to speed up the process :slightly_frowning_face: j

**Comment by utkarsh2102** [comment]
Okay, I'll be happy to help with this! 😄
